### ISSUE TITLE
Rails 6.1 logging error: undefined method 'value_for_database'

### ISSUE THREAD

**Issue by adurgin** [jruby/activerecord-jdbc-adapter#1088]
After updating an application to Rails 6.1.3.1 with activerecord-jdbc-adapter 61.0 and activerecord-jdbcpostgresql-adapter 61.0 a log failure appears with regularity.

Could not log "sql.active_record" event. NoMethodError: undefined method `value_for_database' for 266:Integer ["org/jruby/RubyArray.java:2577:in `map'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-61.0-java/lib/arjdbc/abstract/core.rb:65:in `extract_raw_bind_values'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-61.0-java/lib/arjdbc/abstract/core.rb:71:in `block in log'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/log_subscriber.rb:64:in `type_casted_binds'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/log_subscriber.rb:46:in `sql'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/subscriber.rb:150:in `finish'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/log_subscriber.rb:115:in `finish'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/fanout.rb:157:in `finish'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/fanout.rb:63:in `block in finish'", "org/jruby/RubyArray.java:1809:in `each'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/fanout.rb:63:in `finish'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:30:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-61.0-java/lib/arjdbc/abstract/core.rb:73:in `log'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-61.0-java/lib/arjdbc/abstract/database_statements.rb:46:in `exec_query'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `block in select_all'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block in synchronize'", "org/jruby/RubyThread.java:759:in `handle_interrupt'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'", "org/jruby/RubyThread.java:759:in `handle_interrupt'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-61.0-java/lib/arjdbc/abstract/database_statements.rb:86:in `select_all'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/querying.rb:47:in `find_by_sql'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:849:in `block in exec_queries'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:867:in `skip_query_cache_if_necessary'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:834:in `exec_queries'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:638:in `load'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader/association.rb:118:in `records_for'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader/association.rb:45:in `load_records'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader/association.rb:27:in `records_by_owner'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader/association.rb:17:in `run'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:151:in `block in preloaders_for_reflection'", "org/jruby/RubyHash.java:1415:in `each'", "org/jruby/RubyEnumerable.java:886:in `map'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:150:in `preloaders_for_reflection'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:119:in `block in preloaders_for_hash'", "org/jruby/RubyHash.java:1415:in `each'", "org/jruby/RubyEnumerable.java:940:in `flat_map'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:118:in `block in preloaders_for_hash'", "org/jruby/RubyHash.java:1415:in `each'", "org/jruby/RubyEnumerable.java:940:in `flat_map'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:117:in `preloaders_for_hash'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:108:in `preloaders_on'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:94:in `block in preload'", "org/jruby/RubyArray.java:1809:in `each'", "org/jruby/RubyEnumerable.java:940:in `flat_map'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/associations/preloader.rb:93:in `preload'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:769:in `block in preload_associations'", "org/jruby/RubyArray.java:1809:in `each'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:767:in `preload_associations'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:852:in `block in exec_queries'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:867:in `skip_query_cache_if_necessary'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:834:in `exec_queries'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:638:in `load'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:249:in `records'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:724:in `blank?'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/core_ext/object/blank.rb:26:in `present?'", "/data1/dev/webapp/app/views/history/index.html.haml:18:in `_app_views_history_index_html_haml__542586393_5226'", "org/jruby/RubyKernel.java:1960:in `public_send'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/base.rb:247:in `_run'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/template.rb:154:in `block in render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:205:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/template.rb:345:in `instrument_render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/template.rb:152:in `render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:61:in `block in render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:11:in `render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:117:in `block in _render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/base.rb:273:in `in_rendering_context'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:116:in `_render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:103:in `render_to_body'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/abstract_controller/rendering.rb:25:in `render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/rendering.rb:36:in `render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/stdlib/benchmark.rb:308:in `realtime'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:45:in `render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'", "org/jruby/RubyKernel.java:1897:in `tap'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:228:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actiontext-6.1.3.1/lib/action_text/rendering.rb:20:in `with_renderer'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actiontext-6.1.3.1/lib/action_text/engine.rb:55:in `block in Engine'", "org/jruby/RubyBasicObject.java:2694:in `instance_exec'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activerecord-6.1.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:165:in `process'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:39:in `process'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:190:in `dispatch'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:254:in `dispatch'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'", "org/jruby/RubyArray.java:1809:in `each'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:842:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:98:in `run_callbacks'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:22:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/web-console-4.1.0/lib/web_console/middleware.rb:132:in `call_app'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/web-console-4.1.0/lib/web_console/middleware.rb:28:in `block in call'", "org/jruby/RubyKernel.java:1189:in `catch'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:37:in `call_app'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:26:in `block in call'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:37:in `tagged'", "/data1/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `tagged'"]

**Comment by imustafin** [comment]
Hi. I also encountered this issue some time ago.

Maybe something like this https://github.com/imustafin/activerecord-jdbc-adapter/commit/947069a6d3d88b2c2e523a7cb5e2f695c0907fc2 can help. This is included in #1087

**Comment by masry707** [comment]
Hi, I have the same issue too,

OS: Linux
JRuby: 9.2.17.0
RAILS: 6.1.3.2
activerecord-jdbc-adapter: 61.0
activerecord-jdbcpostgresql-adapter: 61.0

**Comment by JesseChavez** [comment]
This issue seems to go away the the below pull request in Rails

https://github.com/rails/rails/pull/41068

**Comment by cegprakash** [comment]
I have the same issue in Rails 7.1.5.1 and activerecord-jdbc-adapter-71.0-java

```
NoMethodError: undefined method `value_for_database' for :environment:Symbol
```

**Comment by adurgin** [comment]
> I have the same issue in Rails 7.1.5.1 and activerecord-jdbc-adapter-71.0-java
> 
> ```
> NoMethodError: undefined method `value_for_database' for :environment:Symbol
> ```

I have the same versions and am using postgres.  No recent memory of seeing this error.  I don't recall when it stopped happening.

What jruby version are you using, 9.4?

**Comment by cegprakash** [comment]
I'm on `jruby-9.4.13.0`

**Comment by cegprakash** [comment]
In `database.yml` after setting 
```
prepared_statements: false
```
this is resolved for me.
