### ISSUE TITLE
activerecord-jdbcsqlite3-adapter v61.1 is not working with activerecord v6.1.5

### ISSUE THREAD

**Issue by AndyObtiva** [jruby/activerecord-jdbc-adapter#1106]
`jruby -v`

```
jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 Java HotSpot(TM) 64-Bit Server VM 18+36-2087 on 18+36-2087 +jit [darwin-x86_64]
```

`uname -a`

```
Darwin Andys-MacBook-Pro-13.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64 x86_64
```

My gem versions are:

```ruby
gem 'activerecord', '~> 6.1.5'
gem 'activerecord-jdbcsqlite3-adapter', '~> 61.1', :platform => :jruby
```

When I run the following code in IRB:

```ruby
require 'active_record'
require 'activerecord-jdbcsqlite3-adapter' if defined? JRUBY_VERSION
@connection = ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/database.sqlite3')
```

I get the following output and error:

```ruby
jruby-9.3.3.0 :001 > require 'active_record'
 => true 
jruby-9.3.3.0 :004 > require 'activerecord-jdbcsqlite3-adapter' if defined? JRUBY_VERSION
 => true 
jruby-9.3.3.0 :005 > @connection = ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/database.sqlite3')
Traceback (most recent call last):
       16: from org/jruby/RubyKernel.java:1237:in `catch'
       15: from org/jruby/RubyKernel.java:1507:in `loop'
       14: from org/jruby/RubyKernel.java:1091:in `eval'
       13: from (irb):5:in `evaluate'
       12: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activerecord-6.1.5/lib/active_record/connection_handling.rb:52:in `establish_connection'
       11: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1046:in `establish_connection'
       10: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1205:in `resolve_pool_config'
        9: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
        8: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
        7: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
        6: from /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:96:in `require'
        5: from org/jruby/RubyKernel.java:1017:in `require'
        4: from /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager/gems/activerecord-6.1.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:13:in `<main>'
        3: from /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        2: from /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/dependency.rb:323:in `to_spec'
        1: from /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/dependency.rb:311:in `to_specs'
LoadError (Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? Could not find 'sqlite3' (~> 1.4) among 131 total gem(s))
Checked in 'GEM_PATH=/Users/andymaleh/.rvm/gems/jruby-9.3.3.0@contact_manager:/Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/gems/shared' , execute `gem env` for more information
```

I even tried to add the following 2 extra lines to the code (line 2 and 3), but to no avail:

```ruby
require 'active_record'
require 'jdbc/sqlite3'
Jdbc::SQLite3.load_driver
require 'activerecord-jdbcsqlite3-adapter' if defined? JRUBY_VERSION
@connection = ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/database.sqlite3')
```

The original code above used to work with older versions of activerecord (5.2.4.3) and activerecord-jdbcsqlite3-adapter (52.6). I am not sure if I am perhaps mixing the wrong version combinations of the two gems.

Help is appreciated!

**Comment by rubycoder** [comment]
Using JRuby 9.3.4.0 on Windows 7 SP1, with the same versions of the gems, I get the same error from IRB that @AndyObtiva  did.

I then manually applied the pull request from @terencechow  https://github.com/jruby/activerecord-jdbc-adapter/pull/1096 which resolved the error:

```
irb(main):001:0> require 'active_record'
=> true
irb(main):002:0> require 'activerecord-jdbcsqlite3-adapter' if defined? JRUBY_VERSION
=> true
irb(main):003:0> @connection = ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/database.sqlite3')
=> #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x738a39cc @connection_klass=ActiveRecord::Base, @connections=[], @thread_cac
hed_conns=#<Concurrent::Map:0x40738846 entries=0 default_proc=nil>, @checkout_timeout=5.0, @mon_data_owner_object_id=4020, @now_con
necting=0, @pool_config=#<ActiveRecord::ConnectionAdapters::PoolConfig:0x6de33fde @connection_klass=ActiveRecord::Base, @db_config=
#<ActiveRecord::DatabaseConfigurations::HashConfig:0x1255de25 @name="primary", @env_name="default_env", @configuration_hash={:adapt
er=>"sqlite3", :database=>"db/database.sqlite3"}>, @_mutex=#<Thread::Mutex:0x5891b7c5>, @pool=#<ActiveRecord::ConnectionAdapters::C
onnectionPool:0x738a39cc ...>>, @automatic_reconnect=true, @threads_blocking_new_connections=0, @mon_data=#<Monitor:0x4fc3529>, @av
ailable=#<ActiveRecord::ConnectionAdapters::ConnectionPool::ConnectionLeasingQueue:0x38e46765 @lock=#<ActiveRecord::ConnectionAdapt
ers::ConnectionPool:0x738a39cc ...>, @queue=[], @cond=#<MonitorMixin::ConditionVariable:0x192f5f39 @monitor=#<Monitor:0x4fc3529>, @
cond=#<Thread::ConditionVariable:0x4cd5fc46>>, @num_waiting=0>, @idle_timeout=300.0, @db_config=#<ActiveRecord::DatabaseConfigurati
ons::HashConfig:0x1255de25 @name="primary", @env_name="default_env", @configuration_hash={:adapter=>"sqlite3", :database=>"db/datab
ase.sqlite3"}>, @query_cache_enabled=#<Concurrent::Map:0x2965dd88 entries=0 default_proc=#<Proc:0x3221588e@C:/Ruby/jruby-9.3.4.0/li
b/ruby/gems/shared/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:32>>, @size=5, @reaper=#<A
ctiveRecord::ConnectionAdapters::ConnectionPool::Reaper:0x51141f64 @pool=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x738a3
9cc ...>, @frequency=60.0>, @lock_thread=false>
irb(main):004:0>
```

**Comment by AndyObtiva** [comment]
@headius is there any chance the PR @rubycoder mentioned could be merged sometime soon? This gem is the main library used in Glimmer DSL for SWT desktop apps for including a SQLite database with ActiveRecord. I realize that users could revert to an older working version as a workaround, but it’s a shame they could not use the latest version reliably. I have been asked by someone to provide a blog post tutorial on how to integrate SQLite and ActiveRecord with a Glimmer DSL for SWT desktop app. But, this issue is a blocker.

**Comment by AndyObtiva** [comment]
I just added a note to my last comment about the fact that I am using a Mac M1 Chip ARM64 CPU architecture.

```
% uname -a
Darwin Andys-Lexop-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
```

That might be related to this last error. I noted it on the opened issue on the sass-rails project too.

**Comment by enebo** [comment]
@AndyObtiva yeah that is something I am not seeing but it has to be related to M1 and how sassc is specified.

I have released 61.2 which applied #1096.  So you should be able to establish_connection in the way you wrote above.  Rails must have some additional magic which is unclear to me but I can run Rails itself before or after the PR.  I personally like that the PR limits the range of this special require behavior.

I will apologize on all three issues/prs that this got lost in the fog.  Thanks for pinging us again.

**Comment by AndyObtiva** [comment]
I just confirmed that I could install and build a Rails 6.1.5 app in JRuby 9.3.3.0 just fine on an Intel Mac machine, so the issue that I reported at sass-rails is limited to M1 Chip Macs (ARM64) only.

Thank you @enebo for the release. I just tested it and confirmed it resolves the issue.

**Comment by headius** [comment]
The arch issue should be fixed in JRuby 9.3.4.0. there was a set of changes there to correct the arch flag to be arm64 on MacOS.

**Comment by AndyObtiva** [comment]
I just tried installing Rails 6.1.5 in JRuby 9.3.4.0 on my Intel Mac, creating a new app, starting the server, and creating the database, and it all worked, just like JRuby 9.3.3.0 on the Intel Mac.

**Comment by AndyObtiva** [comment]
I just documented the newly discovered ARM64 Mac issue in a separate GitHub issue:
https://github.com/jruby/activerecord-jdbc-adapter/issues/1113

Otherwise, thanks again for resolving this GitHub issue.
