### ISSUE TITLE
Rails 7.1 support

### ISSUE THREAD

**Issue by mullermp** [jruby/activerecord-jdbc-adapter#1146]
Hello. The README suggests that the gem 71.x should support Rails 7.1 but I don't see any of these versions published to https://rubygems.org/gems/activerecord-jdbc-adapter or for the adapters.

**Comment by headius** [comment]
If my assessment is correct, 7.1 support is pretty solid for SQLite, nearly solid for MySQL, and still needs work for PostgreSQL. We know we need to get these out, plus 7.2 support, but we have been bogged down with lots of other issues the past few months.

@kares @enebo What's the status here?

**Comment by enebo** [comment]
@headius you have the right summary.  we just need some time to get to this or some more help (which we got quite a bit a couple of months ago).

**Comment by mullermp** [comment]
How can I help? Do you have existing tests that would verify the completeness of those adapters when they are fully upgraded? What is the acceptance criteria to be ready for release?

**Comment by headius** [comment]
@RTrampov It's a high priority but we are very resource-limited. 😫

My assessment above has not changed. We will try to get something out soon at least for SQLite and MySQL. We need help with PG... if you or someone else here can assist, stop by our [Matrix channel](https://matrix.to/#/#jruby:matrix.org) and we'll get you set up!

**Comment by JesseChavez** [comment]
Hi everyone, 

The adapter has a decent support for Rails 7.1 and 7.2, I did more testing for Rails 7.2 and at the moment I haven't see any issue in my internal CI for several JRuby on Rails applications

There are still some things to be done, just from the top of my head

- Message pack support (pending)
- Tomcat/Jetty support (very likely broken, active record changed how to handle db connections, this adapter used to use some callbacks to pass the db connection to Tomcat)
- and other edge cases that I forget. 

It would be good you guys try the adapter from `master` branch or my fork

sqlite
```
platforms :ruby do
  # Use sqlite3 as the database for Active Record
  gem "sqlite3", ">= 1.4"
end

platforms :jruby do
  # gem 'activerecord-jdbc-adapter', path: '../../vendor_gems/activerecord-jdbc-adapter'
  gem "activerecord-jdbc-alt-adapter", "~> 72.0.0.rc1"
  gem "jdbc-sqlite3"
end
```

postgres
```
platforms :ruby do
  # Use postgresql as the database for Active Record
  gem "pg", "~> 1.1"
end

platforms :jruby do
  # gem 'activerecord-jdbc-adapter', path: '../../vendor_gems/activerecord-jdbc-adapter'
  gem "activerecord-jdbc-alt-adapter", "~> 72.0.0.rc1"
  gem "jdbc-pgsql"
end
```

Any issue you find please file a ticket here I will look at it

Thanks

**Comment by pboling** [comment]
@JesseChavez When I use the following:

```ruby
  platforms :jruby do
    gem "activerecord-jdbc-adapter", github: "JesseChavez/activerecord-jdbc-adapter", branch: "stable-dev"
    gem "activerecord-jdbcsqlite3-adapter", github: "JesseChavez/activerecord-jdbc-adapter", branch: "stable-dev"
    gem "jdbc-sqlite3", github: "JesseChavez/activerecord-jdbc-adapter", branch: "stable-dev"
  end
```

I get this error:

```
An error occurred while installing activerecord-jdbc-adapter (72.0.0.rc1), and
Bundler cannot continue.

In ar_7_2.gemfile:
  activerecord-jdbcsqlite3-adapter was resolved to 72.0.0.rc1, which depends on
    activerecord-jdbc-adapter
``` 

What's the right way to do this?

**Comment by JesseChavez** [comment]
the easiest would be:

```
platforms :jruby do
  gem "activerecord-jdbc-alt-adapter", "~> 72.0.0.rc1"
  gem "jdbc-sqlite3"
end
```

the more complex way would be:

```
platforms :jruby do
    gem "activerecord-jdbc-adapter", github: "JesseChavez/activerecord-jdbc-adapter", branch: "stable-dev"

    gem "jdbc-sqlite3"
end
```

**Comment by pboling** [comment]
Also, I see that both your fork and jruby's master are targeting Rails ~> 7.2.2.

Is there no way to target builds against Rails 8?

**Comment by pboling** [comment]
@JesseChavez @enebo 

When targeting 72-stable I get this:

```
Could not find gem 'activerecord-jdbc-adapter (~> 72.0) jruby' in
https://github.com/jruby/activerecord-jdbc-adapter.git (at 72-stable@c56c7b4).

The source contains the following gems matching 'activerecord-jdbc-adapter':
  * activerecord-jdbc-adapter-71.0-java
```

It looks like there are a bunch of version.rb files, and perhaps some of them got missed?

**Comment by pboling** [comment]
I've created a new issue to track Rails 7.2 support, as it doesn't belong here.
https://github.com/jruby/activerecord-jdbc-adapter/issues/1175

**Comment by cegprakash** [comment]
I'm facing the below issue with Rails 7.1.5.1, activerecord-jdbc-adapter-71.0-java, postgres DB
```
NoMethodError: undefined method `value_for_database' for :environment:Symbol
```

**Comment by chadlwilson** [comment]
> I'm facing the below issue with Rails 7.1.5.1, activerecord-jdbc-adapter-71.0-java, postgres DB
> 
> ```
> NoMethodError: undefined method `value_for_database' for :environment:Symbol
> ```

I also managed to get this during a `rails db:migrate`, but didn't really track it down further.

Not sure if it's just during the migration, the logging, or something else. 

```
$ bundle exec rails db:migrate
Could not log "sql.active_record" event. NoMethodError: undefined method `value_for_database' for :environment:Symbol

org/jruby/RubyArray.java:2840:in `map'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-71.0-java/lib/arjdbc/abstract/core.rb:63:in `block in log'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/log_subscriber.rb:83:in `type_casted_binds'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/log_subscriber.rb:54:in `sql'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/subscriber.rb:137:in `call'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/log_subscriber.rb:151:in `call'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:181:in `block in finish'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'
org/jruby/RubyArray.java:2018:in `each'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:125:in `each'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:180:in `finish'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:262:in `block in finish_with_values'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'
org/jruby/RubyArray.java:2018:in `each'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:261:in `finish_with_values'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/fanout.rb:254:in `finish'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/notifications/instrumenter.rb:64:in `instrument'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-71.0-java/lib/arjdbc/abstract/core.rb:65:in `log'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-71.0-java/lib/arjdbc/abstract/database_statements.rb:51:in `block in internal_exec_query'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activesupport-7.1.5.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-71.0-java/lib/arjdbc/abstract/database_statements.rb:47:in `internal_exec_query'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:115:in `select_all'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-71.0-java/lib/arjdbc/abstract/database_statements.rb:84:in `select_all'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/internal_metadata.rb:147:in `select_entry'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/internal_metadata.rb:99:in `update_or_create_entry'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/internal_metadata.rb:42:in `[]='
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/migration.rb:1510:in `record_environment'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/migration.rb:1502:in `migrate_without_lock'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/migration.rb:1450:in `migrate'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/migration.rb:1274:in `up'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/migration.rb:1249:in `migrate'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/activerecord-7.1.5.1/lib/active_record/railties/databases.rake:93:in `block in <main>'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/task.rb:281:in `block in execute'
org/jruby/RubyArray.java:2018:in `each'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/task.rb:281:in `execute'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
org/jruby/ext/monitor/Monitor.java:82:in `synchronize'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/task.rb:188:in `invoke'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:188:in `invoke_task'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:138:in `block in top_level'
org/jruby/RubyArray.java:2018:in `each'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:138:in `block in top_level'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:147:in `run_with_threads'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:132:in `top_level'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/application.rb:214:in `standard_exception_handling'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/rake-13.3.0/lib/rake/rake_module.rb:59:in `with_application'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/command.rb:156:in `invoke_rake'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/command.rb:73:in `block in invoke'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/command.rb:149:in `with_argv'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/command.rb:69:in `invoke'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/gems/shared/gems/railties-7.1.5.1/lib/rails/commands.rb:18:in `<main>'
org/jruby/RubyKernel.java:1187:in `require'
/Users/chad/.local/share/mise/installs/ruby/jruby-9.4.14.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:37:in `require'
bin/rails:4:in `<main>'
```

**Comment by cegprakash** [comment]
@chadlwilson Try setting `prepared_statements: false` in `database.yml`. That resolved the issue for me.
