### ISSUE TITLE
cannot load Java class com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by cap10morgan** [jruby/activerecord-jdbc-adapter#302]
I'm getting the error "cannot load Java class com.mysql.jdbc.Driver" when using this on JRuby 1.7.1 and 1.7.2, even with jdbc-mysql gem installed.

Steps to reproduce:
- Install JRuby 1.7.2
- Install Rails 3.2.10 under JRuby
- Create a new Rails app and set it up to use MySQL with the following config/database.yml:

```
development:
  adapter: jdbc
  driver: com.mysql.jdbc.Driver
  username: [username]
  password: [password]
  url: jdbc:mysql://localhost:3306/[db_name]
```
- Add activerecord-jdbcmysql-adapter to the Gemfile
- Add jdbc-mysql to the Gemfile (optional; it fails either way, but this is a traditionally suggested fix for this issue that does NOT fix the problem)
- The full Gemfile should look like this: https://gist.github.com/4487540
- Run `bundle install`
- Run `rake db:setup --trace` (or any other command that attempts to initialize the DB connection) in the Rails app's dir

Result:

```
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke rails_env (first_time)
** Execute rails_env
** Execute db:create
** Invoke environment (first_time)
** Execute environment
rake aborted!
The driver encountered an unknown error: cannot load Java class com.mysql.jdbc.Driver
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-1.2.5/lib/arjdbc/jdbc/connection.rb:88:in `initialize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-1.2.5/lib/arjdbc/jdbc/adapter.rb:31:in `initialize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-1.2.5/lib/arjdbc/jdbc/connection_methods.rb:6:in `jdbc_connection'
org/jruby/RubyBasicObject.java:1665:in `__send__'
org/jruby/RubyKernel.java:2090:in `send'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `checkout'
org/jruby/RubyKernel.java:1392:in `loop'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `checkout'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/model_schema.rb:308:in `clear_cache!'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activerecord-3.2.10/lib/active_record/railtie.rb:97:in `_callback_before_7'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/callbacks.rb:421:in `_run__249005193__prepare__2066049634__callbacks'
org/jruby/RubyBasicObject.java:1659:in `__send__'
org/jruby/RubyKernel.java:2086:in `send'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/callbacks.rb:390:in `_run_prepare_callbacks'
org/jruby/RubyBasicObject.java:1659:in `__send__'
org/jruby/RubyKernel.java:2086:in `send'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/actionpack-3.2.10/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/actionpack-3.2.10/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/application/finisher.rb:47:in `Finisher'
org/jruby/RubyBasicObject.java:1720:in `instance_exec'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/initializable.rb:30:in `run'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/initializable.rb:55:in `run_initializers'
org/jruby/RubyArray.java:1613:in `each'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/application.rb:136:in `initialize!'
org/jruby/RubyBasicObject.java:1659:in `__send__'
org/jruby/RubyKernel.java:2086:in `send'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ubuntu/testapp/config/environment.rb:5:in `(root)'
org/jruby/RubyKernel.java:1027:in `require'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/activesupport-3.2.10/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/application.rb:1:in `(root)'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/application.rb:103:in `require_environment!'
org/jruby/RubyProc.java:249:in `call'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/railties-3.2.10/lib/rails/application.rb:297:in `initialize_tasks'
org/jruby/RubyArray.java:1613:in `each'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:228:in `execute'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:166:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
org/jruby/RubyArray.java:1613:in `each'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:187:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:185:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:165:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
org/jruby/RubyArray.java:1613:in `each'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:187:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:185:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:165:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
org/jruby/RubyArray.java:1613:in `each'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:101:in `top_level'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:101:in `top_level'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:73:in `run'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/lib/ruby/gems/shared/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
org/jruby/RubyKernel.java:1046:in `load'
/home/ubuntu/.rbenv/versions/jruby-1.7.2/bin/rake:23:in `(root)'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
```

Expected result:

Rake successfully runs the db:setup task via JDBC's MySQL driver provided by the jdbc-mysql gem.

**Comment by jayeshvethekar** [comment]
what is master here , I am facing same issue with jdbc driver.
