### ISSUE TITLE
In rails 4.2.0.beta1 NoMethodError: undefined method `primary='

### ISSUE THREAD

**Issue by kwando** [jruby/activerecord-jdbc-adapter#576]
````
NoMethodError: undefined method `primary=' for #<ActiveRecord::ConnectionAdapters::MSSQLColumn:0x4f9e9c21>
	from arjdbc/jdbc/RubyJdbcConnection.java:1098:in `columns'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-jdbc-adapter-1.3.9/lib/arjdbc/jdbc/adapter.rb:322:in `columns'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-jdbc-adapter-1.3.9/lib/arjdbc/mssql/adapter.rb:540:in `columns'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/attributes.rb:85:in `columns'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/model_schema.rb:260:in `column_names'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/relation/calculations.rb:226:in `aggregate_column'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/relation/calculations.rb:252:in `execute_simple_calculation'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/relation/calculations.rb:221:in `perform_calculation'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/relation/calculations.rb:127:in `calculate'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/relation/calculations.rb:42:in `count'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/activerecord-4.2.0.beta1/lib/active_record/querying.rb:13:in `count'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/railties-4.2.0.beta1/lib/rails/commands/console.rb:110:in `start'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/railties-4.2.0.beta1/lib/rails/commands/console.rb:9:in `start'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/railties-4.2.0.beta1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/railties-4.2.0.beta1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/kwando/projects/work/sdf_gateway/vendor/bundle/jruby/1.9/gems/railties-4.2.0.beta1/lib/rails/commands.rb:17:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from /Users/kwando/projects/work/sdf_gateway/bin/rails:1:in `(root)'
	from org/jruby/RubyKernel.java:1081:in `load'
	from -e:1:in `(root)'


rails 4.2.0.beta1
gem 'rails', '4.2.0.beta1'
gem 'activerecord-jdbcmssql-adapter', '~> 1.3'
gem 'jdbc-mssql-azure', '0.0.2'

**Comment by kares** [comment]
there was another report for the same issue at #609 ... we do have this one fixed and will be in **1.3.14**
