### ISSUE TITLE
Problem reading postgresql table with binary/bytea column

### ISSUE THREAD

**Issue by ninkibah** [jruby/activerecord-jdbc-adapter#651]
I'm trying to upgrade our project to Rails 4.2.1, and when I try to load data from a table with a bytea column, created using t.binary in the migration file, I get an error:

`uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Bytea::PGconn`

I have tried this with both master and 1.3.6, with the same problem. A sample stack trace is:

```
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:9:in `type_cast_from_database'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:104:in `type_cast'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:42:in `original_value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:37:in `value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_set.rb:31:in `fetch_value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:87:in `read_attribute'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods.rb:305:in `attribute_for_inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:444:in `inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:442:in `collect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:442:in `inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
 ```

This was not a problem with Rails 4.1.6 or earlier.

Has anyone else seen this problem. Google was not helpful in this regard.

The fix is to implement PGconn.unescape_bytea, which is what I may end up doing.

**Comment by kares** [comment]
4.2 support esp. the PostgreSQL adapter is not complete ... I recommend to stay at AR 4.1.x for now (and use the latest AR-JDBC 1.3.x release) ... alternatively you can help us get 4.2 support at #599

**Comment by ninkibah** [comment]
@kares We have decided to go on migrating to Rails 4.2, and if during testing, we find we are getting stability problems due to ARJDBC, then we will drop back to 4.1.
