### ISSUE TITLE
ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR insufficient data left in message:

### ISSUE THREAD

**Issue by dasibre** [jruby/activerecord-jdbc-adapter#685]
When updating a record who's input comes from a textfield of a form and the string contains any null characters, I get the following errors.  Naturally, one can clean up the strings by removing any null byte characters but I'm hoping to avoid doing that unless i have to. I'm wondering if this is can be fixed in the jdbc adapter? 

using activerecord-jdbc-adapter 1.3.16 with postgres 9.1
```
org.postgresql.util.PSQLException: ERROR: insufficient data left in message
  arjdbc/jdbc/RubyJdbcConnection.java:633:in `execute_update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/adapter.rb:492:in `exec_update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `log'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:19:in `instrument'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/adapter.rb:492:in `exec_update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:19:in `update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/relation.rb:88:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/persistence.rb:513:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/locking/optimistic.rb:79:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods/dirty.rb:127:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:310:in `_update_record'
  org/jruby/RubyProc.java:271:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `compile'
  org/jruby/RubyProc.java:271:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:780:in `_run_update_callbacks'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:310:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/timestamp.rb:70:in `_update_record'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/persistence.rb:502:in `create_or_update'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:302:in `create_or_update'
  org/jruby/RubyProc.java:271:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
  /Users/jnaadjie/.rvm/gems/jruby-1.7.20.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `compile'
  org/jruby/RubyProc.java:271:in `call'
```

**Comment by kares** [comment]
does it work with Rails under MRI ? ... alternatively you can try **prepared_statement: true**

**Comment by kares** [comment]
closing - no feedback received.
