### ISSUE TITLE
FreeBSD activerecord-jdbcsqlite3-adapter fails to create or connect to database

### ISSUE THREAD

**Issue by bgalbrecht** [jruby/activerecord-jdbc-adapter#728]
While I am using FreeBSD 10.2-RELEASE-p7 and JRuby 9.1.1.0, this has been failing for several months, and was also failing on JRuby 1.7.x and 9.0.0.0.
[sqlite_issue.txt](https://github.com/jruby/activerecord-jdbc-adapter/files/278634/sqlite_issue.txt)
##

**Comment by kares** [comment]
seems like a problem with SQLite itself (but I can not confirm without a FreeBSD machine).
you could try `-Darjdbc.debug.trace=true` or monkey-patch around the error if there's a Java cause.

**Comment by bgalbrecht** [comment]
Here is a trace with -Darjdbc.debug.trace=true -Darjdbc.debug=true

[sqlite1.txt](https://github.com/jruby/activerecord-jdbc-adapter/files/279979/sqlite1.txt)

**Comment by kares** [comment]
the trace confirms its a native library loading issue under FreeBSD : 
```
Caused by: java.lang.Exception: No native library is found for os.name=FreeBSD and os.arch=x86_64
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
        at org.sqlite.core.NativeDB.load(NativeDB.java:53)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
```
thus this one is blocked by https://github.com/xerial/sqlite-jdbc/issues/106

**Comment by kares** [comment]
should be good with latest jdbc-sqlite3
