### ISSUE TITLE
MySQL adapter + Rails 5: NoMethodError: undefined method `accept' for nil:NilClass

### ISSUE THREAD

**Issue by odedd** [jruby/activerecord-jdbc-adapter#745]
I'll start off by saying that I only **suspect** this to be an issue, but it could very well be a misconfiguration issue on my part.

I have a Rails 5 project which I'm trying to migrate from Ruby to JRuby. I'm using the 'rails-5' branch of the activerecord-jdbc-adapter .

The server starts fine, but on my first attempt at interacting with the database (e.g. `User.first`, or any other method that should generate an SQL query) I'm getting a `NoMethodError: undefined method`accept' for nil:NilClass` error. Seems like 'visitor' is null (inside of database_statements.rb).

Gemfile:

``` ruby
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use mysql as the database for Active Record

platform :jruby do
  gem 'jdbc-mysql', github: 'jruby/activerecord-jdbc-adapter', branch: 'rails-5'
  gem 'activerecord-jdbc-adapter', github: 'jruby/activerecord-jdbc-adapter', branch: 'rails-5'
end

platform :ruby do
  gem 'mysql2'
end

# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
...
# QUITE A LOT MORE HERE. I'VE ALREADY TRIED TO COMMENT ALL BUT ESSENTIALS, BUT TO NO AVAIL
```

Database.yml:

``` ruby
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: ...
  password: ...
  socket: /tmp/mysql.sock
```

Full trace of the error:

```
NoMethodError: undefined method `accept' for nil:NilClass
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:39:in `find_by_sql'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:699:in `exec_queries'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:580:in `load'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:260:in `records'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:256:in `to_a'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:561:in `find_nth_with_limit'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:590:in `find_nth_with_limit_and_offset'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:543:in `find_nth'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:122:in `first'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:3:in `first'
    from (irb):1:in `<eval>'
    from org/jruby/RubyKernel.java:983:in `eval'
    from org/jruby/RubyKernel.java:1290:in `loop'
    from org/jruby/RubyKernel.java:1103:in `catch'
    from org/jruby/RubyKernel.java:1103:in `catch'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/odeddavidov/.rvm/gems/jruby-9.1.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top>'
    from org/jruby/RubyKernel.java:944:in `require'
    from /Users/odeddavidov/Gits/ndavidov_collection/bin/rails:1:in `<top>'
    from org/jruby/RubyKernel.java:962:in `load'
    from -e:1:in `<top>'
```

I believe this is an adapter issue, though I'm far from sure.
##

**Comment by pirat8** [comment]
I perceive the same error migrating a rails4 application to rails5 (in "production" mode it is more stable). I use a similar Gemfile like odedd.

undefined method `accept' for nil:NilClass

activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:67:in `select_all'
activerecord (5.0.0.1) lib/active_record/querying.rb:39:in `find_by_sql'
activerecord (5.0.0.1) lib/active_record/relation.rb:699:in `exec_queries'

**Comment by dpod916** [comment]
I am having this same issue as I am trying to migrate my Rails 5 app from ruby to JRuby

**Comment by chenyun** [comment]
I have the same issue while I am using sqlite3.
`  gem 'jdbc-mysql', github: "jruby/activerecord-jdbc-adapter", branch: 'rails-5'
  gem 'activerecord-jdbcsqlite3-adapter', github: "jruby/activerecord-jdbc-adapter", branch: 'rails-5'
`

**Comment by yahonda** [comment]
I believe it has been addressed at `rails-5` branch since https://github.com/jruby/activerecord-jdbc-adapter/commit/cac20bf842d8dfe8a51a0d84bb230da5f10fccbb Also refer #751
