### ISSUE TITLE
ActiveRecord test_unicode_column_name fails with ActiveRecord JDBC Adapter

### ISSUE THREAD

**Issue by yahonda** [jruby/activerecord-jdbc-adapter#762]
### Steps to reproduce:
ActiveRecord `test_unicode_column_name` test gets an error:
```
$ cd rails/activerecord
$ git checkout 5-0-stable
$ bundle
$ ARCONN=jdbcsqlite3 bundle exec ruby -Itest test/cases/base_test.rb -n test_unicode_column_name
```
### Result:

```ruby
$ ARCONN=jdbcsqlite3 bundle exec ruby -Itest test/cases/base_test.rb -n test_unicode_column_name
Using jdbcsqlite3
Run options: -n test_unicode_column_name --seed 53411

# Running:

E

Finished in 1.784000s, 0.5605 runs/s, 0.0000 assertions/s.

  1) Error:
BasicsTest#test_unicode_column_name:
ActiveModel::UnknownAttributeError: unknown attribute '???' for Weird.
    /home/yahonda/git/rails/activemodel/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
    /home/yahonda/git/rails/activemodel/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
    org/jruby/RubyHash.java:1344:in `each'
    /home/yahonda/git/rails/activemodel/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
    /home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
    /home/yahonda/git/rails/activemodel/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
    /home/yahonda/git/rails/activerecord/lib/active_record/core.rb:319:in `initialize'
    /home/yahonda/git/rails/activerecord/lib/active_record/inheritance.rb:65:in `new'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:33:in `create'
    test/cases/base_test.rb:659:in `test_unicode_column_name'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### Environment:
* AR-JDBC `rails-5` branch
* ActiveRecord `5-0-stable` branch
* JRuby version
```
$ ruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 OpenJDK 64-Bit Server VM 25.111-b16 on 1.8.0_111-b16 +jit [linux-x86_64]
```
* Java version
``` 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
```

**Comment by yahonda** [comment]
Closed since it does not reproduce anymore.

```
$ cd rails/activerecord
$ git checkout 5-1-stable
$ bunde
$ ARCONN=jdbcsqlite3 bundle exec ruby -Itest test/cases/base_test.rb -n test_unicode_column_name
```

```ruby
$ ARCONN=jdbcsqlite3 bundle exec ruby -Itest test/cases/base_test.rb -n test_unicode_column_name
Using jdbcsqlite3
Run options: -n test_unicode_column_name --seed 51315

# Running:

.

Finished in 1.055049s, 0.9478 runs/s, 0.9478 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```
