### ISSUE TITLE
MariaDB JDBC 1.5.6 and 1.5.7 drivers fail (ARJDBC 1.3.16)

### ISSUE THREAD

**Issue by jkuchta** [jruby/activerecord-jdbc-adapter#771]
All queries seem to fail with the below error. I am on ARJDBC 1.3.16 but it doesn't look like this has been addressed in any of the recent patches. MariaDB drivers up to 1.5.6 do not have this issue. It looks like MariaDB made some bug fixes to ResultSet in 1.5.6 (https://mariadb.com/kb/en/mariadb/mariadb-connector-j-156-release-notes/)

Error SQL: 'SET  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES''
java.sql.SQLException: Operation not permit on a closed resultSet
       	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.next(MariaSelectResultSet.java:535)
       	at arjdbc.jdbc.RubyJdbcConnection.doMapGeneratedKeys(RubyJdbcConnection.java:3011)
       	at arjdbc.jdbc.RubyJdbcConnection.mapGeneratedKeys(RubyJdbcConnection.java:2994)
       	at arjdbc.jdbc.RubyJdbcConnection.mapGeneratedKeys(RubyJdbcConnection.java:2980)
       	at arjdbc.mysql.MySQLRubyJdbcConnection.mapGeneratedKeysOrUpdateCount(MySQLRubyJdbcConnection.java:91)
       	at arjdbc.jdbc.RubyJdbcConnection$5.call(RubyJdbcConnection.java:556)
       	at arjdbc.jdbc.RubyJdbcConnection$5.call(RubyJdbcConnection.java:547)
       	at arjdbc.jdbc.RubyJdbcConnection.withConnection(RubyJdbcConnection.java:3228)
       	at arjdbc.jdbc.RubyJdbcConnection.withConnection(RubyJdbcConnection.java:3209)
       	at arjdbc.jdbc.RubyJdbcConnection.execute(RubyJdbcConnection.java:547)
       	at arjdbc.jdbc.RubyJdbcConnection$INVOKER$i$1$0$execute.call(RubyJdbcConnection$INVOKER$i$1$0$execute.gen)
       	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
       	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
       	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
       	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
       	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
       	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
       	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
       	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
       	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
       	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
       	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
       	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
       	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
       	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
       	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
       	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
       	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
       	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
       	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
       	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
       	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
       	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
       	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139)
       	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
       	at org.jruby.RubyClass.finvoke(RubyClass.java:624)
       	at org.jruby.runtime.Helpers.invoke(Helpers.java:500)
       	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:355)
       	at arjdbc.jdbc.RubyJdbcConnection.reconnect(RubyJdbcConnection.java:519)
       	at arjdbc.jdbc.RubyJdbcConnection$INVOKER$i$0$0$reconnect.call(RubyJdbcConnection$INVOKER$i$0$0$reconnect.gen)
       	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
       	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
       	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)

Operation not permit on a closed resultSet from arjdbc/jdbc/RubyJdbcConnection.java:547:in `execute' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/adapter.rb:581:in `_execute' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/adapter.rb:555:in `execute' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/mysql/adapter.rb:82:in `configure_connection' from arjdbc/jdbc/RubyJdbcConnection.java:519:in `reconnect!' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/adapter.rb:288:in `reconnect!' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/callbacks.rb:42:in `on_checkout' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:380:in `_run__1477154953__checkout__callbacks' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:470:in `checkout_and_verify' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:375:in `checkout' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:372:in `checkout' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:260:in `connection' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:259:in `connection' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/bundler/gems/activerecord-bogacs-4410af6666c3/lib/active_record/bogacs/default_pool.rb:292:in `with_connection' from lib/migration_helper.rb:32:in `is_postgresql?' from config/initializers/detect_db.rb:12:in `(root)' from org/jruby/RubyKernel.java:1091:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/config/initializers/detect_db.rb:1:in `(root)' from org/jruby/RubyKernel.java:1091:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:1:in `(root)' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/engine.rb:609:in `Engine' from org/jruby/RubyBasicObject.java:1566:in `instance_exec' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/engine.rb:608:in `Engine' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `run_initializers' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:150:in `tsort_each' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:210:in `each_strongly_connected_component_from' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:219:in `each_strongly_connected_component_from' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:208:in `each_strongly_connected_component_from' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `tsort_each_child' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:203:in `each_strongly_connected_component_from' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:183:in `each_strongly_connected_component' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:182:in `each_strongly_connected_component' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:180:in `each_strongly_connected_component' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.20.jar!/META-INF/jruby.home/lib/ruby/1.9/tsort.rb:148:in `tsort_each' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!' from config/environment.rb:159:in `(root)' from org/jruby/RubyKernel.java:1091:in `load' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing' from org/jruby/RubyKernel.java:1072:in `require' from /var/lib/tomcat7/webapps/ROOT/WEB-INF/config/environment.rb:1:in `(root)' from file:/var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-rack-1.1.18.jar!/jruby/rack/rails/environment3.rb:1:in `(root)' from file:/var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-rack-1.1.18.jar!/jruby/rack/rails/environment3.rb:25:in `load_environment'

**Comment by kares** [comment]
this report could have been a bit better esp. if you expect to have it fixed :) 

... I do not mean just the formatting but a reproducable piece would come handy.
looking at the change-logs and there seems to be some fixes that might be related in 1.5.8 and 1.5.7

any chance we can verify this is still an issue with the updates drivers (1.5.9 is latest ATM)?

**Comment by kares** [comment]
there's been a regression with MariaDB drivers but has been fixed since, working versions: 1.5.4, 1.5.8, 1.5.9
